---
- hosts: webservers
  become: true 
  tasks:
    - name: add certbot repo
      apt_repository:
        repo: ppa:certbot/certbot
        state: present

    - name: update apt cache
      apt:
        update-cache: true

    - name: setup nginx
      apt:
        name: nginx
        state: latest
      notify: restart nginx

    - name: setup certbot
      apt:
        name: python-certbot-nginx
        state: latest

    - name: copy fakemail.stream site config
      copy:
        src: templates/webservers/etc/nginx/sites-available/fakemail.stream
        dest: /etc/nginx/sites-available/fakemail.stream
        owner: root
        group: root
        mode: '644'

    - name: enable fakemail.stream site config
      file:
        src: /etc/nginx/sites-available/fakemail.stream
        dest: /etc/nginx/sites-enabled/fakemail.stream
        state: link

  handlers:
    - name: restart nginx
      service:
        name=nginx
        state=restarted

    
