---
- hosts: redis
  become: true 
  tasks:   
  - name: Ensure dependencies installed
    apt: 
      name: 'redis-server'
      state: present
      autoremove: yes
  
  - name: Ensure maxmemory is set to 100 MB
    lineinfile:
      path: /etc/redis/redis.conf
      regexp: '^(# )?maxmemory .*'
      line: maxmemory 100MB

  - name: Ensure password set
    lineinfile:
      path: /etc/redis/redis.conf
      regexp: '^(# )?requirepass .*'
      line: requirepass [password]

  - name: Set maxmemory-policy
    lineinfile:
      path: /etc/redis/redis.conf
      regexp: '^(# )?maxmemory-policy .*'
      line: maxmemory-policy volatile-ttl

  - name: Set transaction log
    lineinfile:
      path: /etc/redis/redis.conf
      regexp: '^(# )?appendonly .*'
      line: appendonly yes

  # this one has an existing value, so don't include the comment char
  - name: Set transaction log flush policy
    lineinfile:
      path: /etc/redis/redis.conf
      regexp: '^appendfsync .*'
      line: appendfsync always

  - name: Restart redis server
    systemd:
      state: restarted
      name: redis-server

