---
- hosts: smtpservers
  become: true 
  tasks:
  - name: Create dir
    file:
      path: /home/ansible/FakemailSmtpServer
      state: directory
      owner: ansible
      group: root
      mode: 0700

  - name: Upload systemd unit file
    copy:
      src: fakemailsmtpserver.service
      dest: /etc/systemd/system
      mode: 0644

  - name: Upload binary
    copy:
      src: ../FakemailSmtpServer/bin/Release/netcoreapp3.1/publish/
      dest: /home/ansible/FakemailSmtpServer
      force: yes

  - name: restart smtp server
    systemd:
      enabled: yes
      state: restarted
      name: fakemailsmtpserver
