all:
  hosts:
    prod:
      ansible_host: fakemail-prod
      ansible_ssh_private_key_file: ~/.ssh/fakemail_admin_ed25519
      public_dns_name: fakemail.stream
      is_public: true
      auto_deploy_branch: production

    test:
      ansible_host: fakemail-test
      ansible_ssh_private_key_file: ~/.ssh/fakemail_admin_ed25519
      public_dns_name: test.fakemail.stream
      is_public: true
      auto_deploy_branch: test

    dev:
       ansible_host: localhost
       ansible_ssh_private_key_file: ~/.ssh/fakemail_admin_ed25519
       public_dns_name: dev.fakemail.stream
       is_public: false
       auto_deploy_branch: dev

  children:
    azure:
      hosts:
      vars:
        ansible_user: azureuser

    oracle_cloud:
      hosts:
        prod:
      vars:
        ansible_user: ubuntu

    local:
      hosts:
        test:
        dev:
      vars:
        ansible_user: root

    webservers:
      hosts:
        prod:
        test:
        dev:

    smtpservers:
      hosts:
        prod:
        test:
        dev:

    fakemailservers:
      hosts:
        prod:
        test:
        dev:
